[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "openai>=1.108.1",
    "playwright>=1.55.0",
    "requests>=2.32.5",
    "tiktokapi>=7.1.0",
    "yt-dlp>=2025.9.5",
]
